// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Dang Dao",
            "email": "ddang.daodang@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/all": {
            "get": {
                "description": "Get the list of all users",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Get users",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "page",
                        "description": "page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "size",
                        "description": "number of elements per page",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "orderBy",
                        "description": "filter name",
                        "name": "orderBy",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UsersList"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/auth/change-password/{user_id}": {
            "put": {
                "description": "Change user password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Change user password",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "login user, returns user and set session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login new user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "logout user removing session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Logout user",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "description": "Get current user by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Get user by id",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "register new user, returns user and token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register new user",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                }
            }
        },
        "/auth/token": {
            "get": {
                "description": "Get CSRF token, required auth session cookie",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Get CSRF token",
                "responses": {
                    "200": {
                        "description": "Ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/auth/{id}": {
            "get": {
                "description": "get string by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "get user by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "user_id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            },
            "delete": {
                "description": "some description",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Delete user account",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "user_id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/auth/{name}": {
            "get": {
                "description": "Find user by name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Find by name",
                "parameters": [
                    {
                        "type": "string",
                        "format": "username",
                        "description": "username",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UsersList"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/auth/{station_code}": {
            "get": {
                "description": "Find user by station code",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Find by station code",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UsersList"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/auth/{user_id}": {
            "put": {
                "description": "update existing user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Update user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "user_id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                }
            }
        },
        "/auth/{user_name}": {
            "get": {
                "description": "Find user by name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Find by name",
                "parameters": [
                    {
                        "type": "string",
                        "format": "username",
                        "description": "username",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/insp/": {
            "post": {
                "description": "Create inspection",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "insp"
                ],
                "summary": "Create inspection",
                "operationId": "Create inspection",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Inspection"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/insp/all": {
            "get": {
                "description": "Get the list of all inspections",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "insp"
                ],
                "summary": "Get all inspections following pagination query(size, page, orderBy",
                "operationId": "GetAll",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "page",
                        "description": "page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "size",
                        "description": "number of elements per page",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "orderBy",
                        "description": "filter name",
                        "name": "orderBy",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.InspectionsList"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/insp/expiry-date": {
            "get": {
                "description": "Get inspections by expiry date",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "insp"
                ],
                "summary": "Get inspections by expiry date",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Month",
                        "name": "month",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Year",
                        "name": "year",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Inspection"
                        }
                    }
                }
            }
        },
        "/insp/inspection-date": {
            "get": {
                "description": "Get inspections by inspection date",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "insp"
                ],
                "summary": "Get inspections by inspection date",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Month",
                        "name": "month",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Year",
                        "name": "year",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.InspectionsList"
                        }
                    }
                }
            }
        },
        "/insp/registration/{registration_id}": {
            "get": {
                "description": "Get inspection by registration id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "insp"
                ],
                "summary": "Get inspection by registration id",
                "operationId": "GetByRegistrationID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "registration_id",
                        "description": "registration id",
                        "name": "registration_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.InspectionsList"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/insp/station/{station_code}": {
            "get": {
                "description": "Get inspection by station code",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "insp"
                ],
                "summary": "Get inspection by station code",
                "operationId": "GetByStationCode",
                "parameters": [
                    {
                        "type": "string",
                        "format": "station_code",
                        "description": "area code",
                        "name": "station_code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.InspectionsList"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/insp/statistic": {
            "get": {
                "description": "Count inspections by quarter and year",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "insp"
                ],
                "summary": "Count inspections by quarter and year",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Year",
                        "name": "year",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.QuarterAndYear"
                        }
                    }
                }
            }
        },
        "/insp/statistic/all": {
            "get": {
                "description": "Count inspections by quarter and year",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "insp"
                ],
                "summary": "Count inspections by quarter and year",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.QuarterAndYear"
                        }
                    }
                }
            }
        },
        "/insp/statistic/region": {
            "get": {
                "description": "Count inspections by region and year",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "insp"
                ],
                "summary": "Count inspections by region and year",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.RegionAndYear"
                        }
                    }
                }
            }
        },
        "/insp/statistic/station/{station_code}": {
            "get": {
                "description": "Count inspections by quarter and year in station",
                "tags": [
                    "insp"
                ],
                "summary": "Count inspections by quarter and year in station",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StationQuarterAndYear"
                        }
                    }
                }
            }
        },
        "/insp/{inspection_id}": {
            "get": {
                "description": "Get inspection by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "insp"
                ],
                "summary": "Get inspection by ID",
                "operationId": "GetByID",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.InspectionsList"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            },
            "put": {
                "description": "Update inspection",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Insp"
                ],
                "summary": "Update inspection",
                "operationId": "Update",
                "parameters": [
                    {
                        "type": "string",
                        "format": "inspection_id",
                        "description": "inspection id",
                        "name": "inspection_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Inspection"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete inspection",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "insp"
                ],
                "summary": "Delete inspection",
                "operationId": "Delete",
                "parameters": [
                    {
                        "type": "string",
                        "format": "inspection_id",
                        "description": "inspection id",
                        "name": "inspection_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/station": {
            "get": {
                "description": "Get all stations",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "station"
                ],
                "summary": "Get all stations",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort by",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Order by",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StationsList"
                        }
                    }
                }
            }
        },
        "/station/{station_code}": {
            "get": {
                "description": "Get station by Code",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "station"
                ],
                "summary": "Get station by Code",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Station Code",
                        "name": "station_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Station"
                        }
                    }
                }
            }
        },
        "/vehicle/details/{registration_id}": {
            "get": {
                "description": "Get vehicle details information by registration ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Vehicles"
                ],
                "summary": "Get vehicle details by registration ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Registration ID",
                        "name": "registration_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.VehiclesAndDetails"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/vehicles": {
            "get": {
                "description": "Get a list of all vehicles",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Vehicles"
                ],
                "summary": "Get all vehicles",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Vehicle"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing vehicle with the provided data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Vehicles"
                ],
                "summary": "Update vehicle",
                "parameters": [
                    {
                        "description": "Vehicle object",
                        "name": "vehicle",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Vehicle"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Vehicle"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new vehicle with the provided data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Vehicles"
                ],
                "summary": "Create a new vehicle",
                "parameters": [
                    {
                        "description": "Vehicle object",
                        "name": "vehicle",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Vehicle"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Vehicle"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/vehicles/{registration_id}": {
            "get": {
                "description": "Get vehicle information by registration ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Vehicles"
                ],
                "summary": "Get vehicle by registration ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Registration ID",
                        "name": "registration_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Vehicle"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an existing vehicle by registration ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Vehicles"
                ],
                "summary": "Delete vehicle",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Registration ID",
                        "name": "registration_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/visitor": {
            "post": {
                "description": "Get visitor by registration ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "visitor"
                ],
                "summary": "Get visitor by registration ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Registration ID",
                        "name": "registration_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Person Identity Number",
                        "name": "person_identity_number",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Visitor"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "httpErrors.RestError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "models.CarsCount": {
            "type": "object",
            "properties": {
                "q1": {
                    "type": "integer"
                },
                "q2": {
                    "type": "integer"
                },
                "q3": {
                    "type": "integer"
                },
                "q4": {
                    "type": "integer"
                }
            }
        },
        "models.CarsCountRegion": {
            "type": "object",
            "properties": {
                "mb": {
                    "type": "integer"
                },
                "mn": {
                    "type": "integer"
                },
                "mt": {
                    "type": "integer"
                }
            }
        },
        "models.Inspection": {
            "type": "object",
            "properties": {
                "expiry_date": {
                    "type": "string"
                },
                "inspection_date": {
                    "type": "string"
                },
                "inspection_id": {
                    "type": "integer"
                },
                "registration_id": {
                    "type": "string"
                },
                "station_code": {
                    "type": "string"
                }
            }
        },
        "models.InspectionsList": {
            "type": "object",
            "properties": {
                "has_more": {
                    "type": "boolean"
                },
                "inspections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Inspection"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "total_count": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "models.Pair": {
            "type": "object",
            "properties": {
                "inspection": {
                    "$ref": "#/definitions/models.Inspection"
                },
                "station": {
                    "$ref": "#/definitions/models.Station"
                }
            }
        },
        "models.QuarterAndYear": {
            "type": "object",
            "properties": {
                "cars_count": {
                    "$ref": "#/definitions/models.CarsCount"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "models.RegionAndYear": {
            "type": "object",
            "properties": {
                "cars_count_region": {
                    "$ref": "#/definitions/models.CarsCountRegion"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "models.Station": {
            "type": "object",
            "required": [
                "province",
                "station_manager",
                "station_name"
            ],
            "properties": {
                "province": {
                    "type": "string"
                },
                "station_address": {
                    "type": "string"
                },
                "station_code": {
                    "type": "string"
                },
                "station_email": {
                    "type": "string"
                },
                "station_hotline": {
                    "type": "string"
                },
                "station_id": {
                    "type": "integer"
                },
                "station_manager": {
                    "type": "string"
                },
                "station_map_source": {
                    "type": "string"
                },
                "station_name": {
                    "type": "string"
                },
                "station_status": {
                    "type": "boolean"
                },
                "station_url": {
                    "type": "string"
                }
            }
        },
        "models.StationQuarterAndYear": {
            "type": "object",
            "properties": {
                "cars_count": {
                    "$ref": "#/definitions/models.CarsCount"
                },
                "station_code": {
                    "type": "string"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "models.StationsList": {
            "type": "object",
            "properties": {
                "has_more": {
                    "type": "boolean"
                },
                "page": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "stations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Station"
                    }
                },
                "total_count": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "models.User": {
            "type": "object",
            "required": [
                "first_name",
                "last_name",
                "password"
            ],
            "properties": {
                "about": {
                    "type": "string",
                    "maxLength": 1024
                },
                "avatar": {
                    "type": "string",
                    "maxLength": 512
                },
                "created_at": {
                    "type": "string"
                },
                "date_of_birth": {
                    "type": "string"
                },
                "email": {
                    "type": "string",
                    "maxLength": 60
                },
                "first_name": {
                    "type": "string",
                    "maxLength": 30
                },
                "gender": {
                    "type": "string"
                },
                "identity_no": {
                    "type": "string",
                    "maxLength": 20
                },
                "last_name": {
                    "type": "string",
                    "maxLength": 30
                },
                "login_date": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "phone_number": {
                    "type": "string",
                    "maxLength": 20
                },
                "role": {
                    "type": "string",
                    "maxLength": 10
                },
                "station_code": {
                    "type": "string",
                    "maxLength": 20
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string",
                    "maxLength": 60
                }
            }
        },
        "models.UsersList": {
            "type": "object",
            "properties": {
                "has_more": {
                    "type": "boolean"
                },
                "page": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "total_count": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.User"
                    }
                }
            }
        },
        "models.Vehicle": {
            "type": "object",
            "required": [
                "brand",
                "chassis_number",
                "color",
                "engine_number",
                "inspection_id",
                "manufactured_country",
                "manufactured_year",
                "model_code",
                "owner_id",
                "place_of_registration",
                "registration_id",
                "vin_id"
            ],
            "properties": {
                "brand": {
                    "type": "string",
                    "maxLength": 255
                },
                "chassis_number": {
                    "type": "string",
                    "maxLength": 255
                },
                "color": {
                    "type": "string",
                    "maxLength": 255
                },
                "engine_number": {
                    "type": "string",
                    "maxLength": 255
                },
                "inspection_id": {
                    "type": "string",
                    "maxLength": 255
                },
                "manufactured_country": {
                    "type": "string",
                    "maxLength": 255
                },
                "manufactured_year": {
                    "type": "integer"
                },
                "model_code": {
                    "type": "string",
                    "maxLength": 255
                },
                "owner_id": {
                    "type": "string"
                },
                "place_of_registration": {
                    "type": "string",
                    "maxLength": 255
                },
                "registration_date": {
                    "type": "string"
                },
                "registration_id": {
                    "type": "string",
                    "maxLength": 255
                },
                "vin_id": {
                    "type": "string",
                    "maxLength": 255
                }
            }
        },
        "models.VehicleDetails": {
            "type": "object",
            "required": [
                "vin_id"
            ],
            "properties": {
                "commercial_use": {
                    "type": "string"
                },
                "design_authorized_pay_load": {
                    "type": "string"
                },
                "design_authorized_total_mass": {
                    "type": "string"
                },
                "design_authorized_towed_mass": {
                    "type": "string"
                },
                "engine_displacement": {
                    "type": "string"
                },
                "equipped_with_camera": {
                    "type": "boolean"
                },
                "equipped_with_tachograph": {
                    "type": "boolean"
                },
                "kerb_mass": {
                    "type": "string"
                },
                "largest_luggage_container_dimension": {
                    "type": "string"
                },
                "laying_place": {
                    "type": "integer"
                },
                "manufactured_year": {
                    "type": "integer"
                },
                "mark": {
                    "type": "string"
                },
                "max_output": {
                    "type": "string"
                },
                "model_code": {
                    "type": "string"
                },
                "modification": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "number_of_tires": {
                    "type": "integer"
                },
                "overall_dimension": {
                    "type": "string"
                },
                "permissible_no_of_per_carried": {
                    "type": "integer"
                },
                "rpm": {
                    "type": "integer"
                },
                "seat": {
                    "type": "integer"
                },
                "stood_place": {
                    "type": "integer"
                },
                "tires_size_axle": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "type_of_fuel_used": {
                    "type": "string"
                },
                "vin_id": {
                    "type": "string"
                },
                "wheel_base": {
                    "type": "string"
                },
                "wheel_formula": {
                    "type": "string"
                },
                "wheel_tread": {
                    "type": "string"
                }
            }
        },
        "models.VehiclesAndDetails": {
            "type": "object",
            "properties": {
                "vehicle": {
                    "$ref": "#/definitions/models.Vehicle"
                },
                "vehicle_details": {
                    "$ref": "#/definitions/models.VehicleDetails"
                }
            }
        },
        "models.Visitor": {
            "type": "object",
            "properties": {
                "pair": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Pair"
                    }
                },
                "vehicle": {
                    "$ref": "#/definitions/models.Vehicle"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "RegistryTotal REST API",
	Description:      "RegistryTotal Golang REST API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
