FROM golang:1.20.4-alpine

#ENV TZ=Europe/Moscow
#RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENV config=docker

#WORKDIR /app

COPY . .

RUN go install github.com/githubnemo/CompileDaemon@latest

RUN go mod init

RUN go mod download


EXPOSE 5000

ENTRYPOINT CompileDaemon --build="go build cmd/api/main.go" --command=./main